### ISSUE TITLE
organization issues template and others shits

### ISSUE THREAD

**Issue by JohnGolgota** [Lana-Software/.github#1]

**Comment by Kolozuz** [comment]
Reopen and made some changes (sorry I forgot to do it in a different branch lmao)

**Comment by Kolozuz** [comment]
Reopened and made some changes using the latest GitHub's Issue Forms syntax.
I forgot to do it in a different branch so sorry for that, I've linked the related commits and will set it closed again for now.

**Comment by JohnGolgota** [comment]
If I were the owner of this, I would have given you a resounding slap for committing directly to the main branch.

**Comment by Kolozuz** [comment]
> If I were the owner of this, I would have given you a resounding slap for committing directly to the main branch.

yeah sorry bout' that, i would slap myself if i was the owner as well :skull:, btw what do you think bout' the features_request template? i mean i like doing those as Issue Forms, looks very clean and professional, would be nice if it had real-time markdown formatting though, i mean md still works, but you just can't see it till you're done submitting the issue
